name: ar_outfitter
description: Demonstrates how to use the arkit_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_rating_bar: ^4.0.0
  latlong2: ^0.8.1
  dio: ^4.0.4
  flutter_map: ^1.1.0
  flutter_dotenv: ^5.0.2
  firebase_storage: ^10.2.9
  uuid: ^3.0.6
  image_picker: ^0.8.4+11
  firebase_core: ^1.17.1
  english_words: ^4.0.0
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  flushbar: ^1.10.4
  google_nav_bar: ^5.0.6
  fluttertoast: ^8.0.9
  flutter_expanded_tile: ^0.3.6
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  arkit_plugin:
    path: ../
  
flutter_icons:
  android: true
  ios: true
  image_path: "arboa/images/ARBOA-logos_transparent.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  assets:
    - .env
    - images/yoboi.png
    - images/marker.png
    - images/ARBOA-logos_transparent.png
    - images/out1.png
    - images/oft.svg
    - images/outfitters.jpg
    - images/out1.jpg
    - images/o2.jpg
    - images/o3.jpg
    - images/o4.jpg
    - images/o5.jpg
    - images/c1.jpg
    - images/c2.jpg
    - images/c3.jpg
    - images/c4.jpg
    - images/c5.jpg
    - images/people.png
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
